width: 800
height: 500
size : !!python/tuple [800,500]

c1 : !!python/tuple [45, 22, 80]
c2 : !!python/tuple [45, 22, 81]
c3 : !!python/tuple [45, 21, 80]
c4 : !!python/tuple [45, 21, 81]
c5 : !!python/tuple [55, 22, 80]
c6 : !!python/tuple [44, 21, 80]
c7 : !!python/tuple [44, 21, 81]
c8 : !!python/tuple [45, 22, 82]
c9 : !!python/tuple [45, 23, 80]
white : !!python/tuple [255, 255, 255]
text : !!python/tuple [255,255,255]
max_circle : !!python/tuple [0,129,112]
green : !!python/tuple [152,216,170] #buttons
error_bridge : !!python/tuple [255,109,96]
bright_green : !!python/tuple [97, 213, 132]
dark_green : !!python/tuple [56, 148, 56] # Title
blur_green : !!python/tuple [243,233,159,50]
circle_green : !!python/tuple [152,216,170, 55.9]